generator:
  features:
    enable:
      # Enables paths client generation
      - 'paths/client'
      # Enables webhooks client generation
      - 'webhooks/client'
      # Enables paths server generation
      - 'paths/server'
      # Enables webhooks server generation
      - 'webhooks/server'
      # Enables client usage in security source implementations
      - 'client/security/reentrant'
      # Enables validation of client requests
      - 'client/request/validation'
      # Enables validation of server responses
      - 'server/response/validation'
      # Enables stub Handler generation
      - 'ogen/unimplemented'
      # Enables example tests generation
      - 'debug/example_tests'
       # Enables OpenTelemetry integration
      - 'ogen/otel'
    disable_all: true