name: yir
  
volumes:
  redpanda-0: 
  minio-s3:
  postgres:

services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    env_file:
      - .env.example
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init-postgres.sh:/docker-entrypoint-initdb.d/init-postgres.sh:ro
    ports:
      - "5432:5432"
    restart: always
    profiles:
      - deps
      - app
    environment:
      POSTGRES_MULTIPLE_DATABASES: authdb,meddb,uzidb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

  minio:
    container_name: minio-s3
    image: minio/minio:RELEASE.2024-10-13T13-34-11Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_SERVER_URL: http://localhost:9000
      MINIO_ACCESS_KEY: NZjt6KmuHQRU7IitYUiW   
      MINIO_SECRET_KEY: ql9DoBMKyqMxQm8j5LQuKwnn68KFsGqn5jGbL7uL    
    volumes:
      - minio-s3:/data
    command: server --address 0.0.0.0:9000 --console-address 0.0.0.0:9001 /data
    profiles:
      - deps
      - app
    restart: always

  ##################
  # Redpanda Brokers #
  ##################
  redpanda-0:
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      # Address the broker advertises to clients that connect to the Kafka API.
      # Use the internal addresses to connect to the Redpanda brokers'
      # from inside the same Docker network.
      # Use the external addresses to connect to the Redpanda brokers'
      # from outside the Docker network.
      - --advertise-kafka-addr internal://redpanda-0:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      # Address the broker advertises to clients that connect to the HTTP Proxy.
      - --advertise-pandaproxy-addr internal://redpanda-0:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      # Redpanda brokers use the RPC API to communicate with each other internally.
      - --rpc-addr redpanda-0:33145
      - --advertise-rpc-addr redpanda-0:33145
      # Mode dev-container uses well-known configuration properties for development in containers.
      - --mode dev-container
      # Tells Seastar (the framework Redpanda uses under the hood) to use 1 core on the system.
      - --smp 1
      - --default-log-level=info
    image: docker.redpanda.com/redpandadata/redpanda:v24.3.1
    container_name: redpanda-0
    volumes:
      - redpanda-0:/var/lib/redpanda/data
    ports:
      - 18081:18081
      - 18082:18082
      - 19092:19092
      - 19644:9644
    profiles:
      - deps 
      - app
  ####################
  # Redpanda Console #
  ####################
  console:
    container_name: redpanda-console
    image: docker.redpanda.com/redpandadata/console:v2.8.0
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console -config.filepath=${CONFIG_FILEPATH:-/tmp/config.yml}'
    volumes:
      - ./config:/tmp/config/
    environment:
      CONFIG_FILEPATH: ${CONFIG_FILEPATH:-/tmp/config.yml}
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda-0:9092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda-0:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda-0:9644"]
    ports:
      - 8081:8080
    depends_on:
      - redpanda-0
    profiles:
      - deps
      - app

  ml_service:
    container_name: ml_service
    build: 
      context: ./ml_service/
      dockerfile: Dockerfile
    depends_on:
      - redpanda-0
    profiles:
      - app
    env_file:
      - ./ml_service/.env-docker

  auth_service:
    container_name: auth_service
    build:
      context: ./auth/
      dockerfile: Dockerfile
    env_file:
      - ./auth/.env-docker
    ports:
      - 50040:50055
    profiles:
      - app

  med_service:
    container_name: med_service
    build:
      context: ./med/
      dockerfile: Dockerfile
    env_file:
      - ./med/.env-docker
    ports:
      - 50050:50055
    profiles:
      - app

  uzi_service:
    container_name: uzi_service
    build:
      context: ./uzi/
      dockerfile: Dockerfile
    env_file:
      - ./uzi/.env-docker
    ports:
      - 50060:50055
    profiles:
      - app
    
  composition_api:
    container_name: composition_api
    build:
      context: ./composition-api/
      dockerfile: Dockerfile
    env_file:
      - ./composition-api/.env-docker
    ports:
      - 8080:50055
    depends_on:
      - redpanda-0
      - uzi_service
      - med_service
      - auth_service
    profiles:
      - app