version: "3"

vars:
  services: [gateway, auth, med, uzi]

tasks:
  inherit-pkg:
    cmds:
      - for: { var: services }
        cmd: rm -rf {{.ITEM}}/pkg && cp -r pkg {{.ITEM}}/pkg
  fix-go-mod:
    cmds:
      - for: { var: services }
        cmd: cd {{.ITEM}} && go mod tidy
