version: '3'

vars:
  VENDOR_PROTOGEN: '../vendor.protogen'

tasks:
  get-proto:
    cmds:
      - cp ../auth/api/auth/auth.proto rpc/auth
      - cp ../uzi/api/grpcapi/uzi.proto rpc/uzi
      - cp ../uzi/api/broker/kafka.proto rpc/broker
      - cp ../med/api/med.proto rpc/med

  inject-tags:
    vars:
      SRC:
        sh: find rpc -type f -name '*.pb.go' | xargs echo
    cmds:
      - for: { var: SRC }
        cmd: protoc-go-inject-tag -input={{.ITEM}}

  generate-rpc:
    desc: "сгенерировать .proto"
    vars:
      PROTO_LIBS:
        sh: find {{.VENDOR_PROTOGEN}} -mindepth 1 -maxdepth 1 -type d | xargs echo

      RPC:
        sh: find rpc -type f -name '*.proto' | xargs echo

    cmds:
      - for: { var: RPC }
        cmd: >
          protoc
          -I {{dir .ITEM}}
          {{range $PROTO_LIB := splitList " " .PROTO_LIBS}}-I {{$PROTO_LIB}} {{end}}
          --go_out {{dir .ITEM}} --go_opt=paths=source_relative
          --go-grpc_out {{dir .ITEM}} --go-grpc_opt=paths=source_relative
          --grpc-gateway_out {{dir .ITEM}} --grpc-gateway_opt logtostderr=true,paths=source_relative
          --openapiv2_out {{dir .ITEM}} --openapiv2_opt=logtostderr=true
          {{.ITEM}}
          
      - task: inject-tags
       

  clean:
    desc: "Удалить сгенерированные файлы"
    vars:
      GENERATED:
        sh: find rpc -type f -regex '.*\.\(go\|json\)' | xargs echo
    cmds:
      - for: { var: GENERATED }
        cmd: rm {{.ITEM}}

  style:
    cmds:
      - go fmt ./...
      - goimports -w .

  build:
    cmds:
      - task: clean
      - task: get-proto
      - task: generate-rpc
      - task: style
      - swag init -g cmd/server.go
      - swag fmt
      - go build -v -o bin/server cmd/server.go

  run:
    deps: [build]
    cmd: ./bin/server

  default:
    - task: run
