version: '3'

vars:
  VENDOR_PROTOGEN: '../vendor.protogen'

tasks:
  generate-rpc:
    desc: "сгенерировать .proto"
    vars:
      PROTO_LIBS:
        sh: find {{.VENDOR_PROTOGEN}} -mindepth 1 -maxdepth 1 -type d | xargs echo

      RPC:
        sh: find rpc -type f -name '*.proto' | xargs echo

    cmds:
      - for: { var: RPC }
        cmd: >
          protoc
          -I {{dir .ITEM}}
          {{range $PROTO_LIB := splitList " " .PROTO_LIBS}}-I {{$PROTO_LIB}} {{end}}
          --go_out {{dir .ITEM}} --go_opt=paths=source_relative
          --go-grpc_out {{dir .ITEM}} --go-grpc_opt=paths=source_relative
          --grpc-gateway_out {{dir .ITEM}} --grpc-gateway_opt logtostderr=true,paths=source_relative
          --openapiv2_out {{dir .ITEM}} --openapiv2_opt=logtostderr=true
          {{.ITEM}}

  clean:
    desc: "Удалить сгенерированные файлы"
    vars:
      GENERATED:
        sh: find rpc -type f -regex '.*\.\(go\|json\)' | xargs echo
    cmds:
      - for: { var: GENERATED }
        cmd: rm {{.ITEM}}

  docs:
    deps: [generate-rpc]
    
