version: '3'

includes:
  root_tasks: ../Taskfile.yml

tasks:
  build:
    - task: root_tasks:build

  run:
    deps: [build]
    env:
      DB_PASS: 1234

    cmds:
      - ./bin/cmd

  default:
    - task: root_tasks:build
