version: '3'

includes:
  root_tasks: ../Taskfile.yml

tasks:
  build:
    - task: root_tasks:build

  run:
    deps: [build]
    env:
      DB_PASS: 1234
      TOKEN_PRIVATE_KEY: 1
      TOKEN_PUBLIC_KEY: 1

    cmds:
      - ./bin/server

  default:
    - task: root_tasks:build
