version: '3'

includes:
  root_tasks: ../Taskfile.yml

tasks:
  build:
    - task: root_tasks:build

  run:
    deps: [build]
    env:
      DB_PASS: 1234
      TOKEN_PRIVATE_KEY: 
        sh: cat '/home/zkryaev/med-git/private.key'
      TOKEN_PUBLIC_KEY: 
        sh: cat '/home/zkryaev/med-git/public.key'

    cmds:
      - ./bin/auth

  default:
    - task: root_tasks:build
