version: "3"

vars:
  VENDOR_PROTOGEN: "../vendor.protogen"

dotenv: [".env"]

tasks:
  bin-deps:
    cmds:
      - GOBIN=$(pwd)/bin go install github.com/pressly/goose/v3/cmd/goose@latest

  codegen:
    vars:
      proto_libs:
        sh: find {{.VENDOR_PROTOGEN}} -mindepth 1 -maxdepth 1 -type d | xargs echo
      proto_files:
        sh: find proto -type f -name "*.proto" | xargs echo

    cmds:
      - for: { var: proto_files }
        cmd: >
          protoc
          -I {{dir .ITEM}}
          {{range $lib := splitList " " .proto_libs}}-I {{$lib}} {{end}}
          --experimental_allow_proto3_optional
          --go_out . --go-grpc_out .
          {{.ITEM}}
  style:
    cmds:
      - go fmt ./...
      - goimports -w .
      - gofumpt -l -w .

  build:
    cmds:
      - task: style
      - go build -v -o bin/service cmd/service/main.go

  run:
    cmds:
      - task: build
      - ./bin/service

  migration-up:
    cmds:
      - goose -dir db/migrations up

  migration-down:
    cmds:
      - goose -dir db/migrations down
