app:
  env: DEV
  host: localhost
  grpc: 50053
  http: 8081

db:
  host: localhost
  port: 5432
  name: authdb
  user: postgres

token:
  access_time: 1m
  refresh_time: 5m

medservice:
  host: localhost
  grpc: 50055
