version: "2"

run:
  timeout: 5m
  tests: false

linters:
  enable:
    - asciicheck
    - dogsled
    - durationcheck
    - errcheck
    - errorlint
    - gofmt
    - goimports
    - gosec
    - misspell
    - nakedret
    - nilerr
    - wsl
    - nolintlint
    - revive
    - wastedassign
    - copyloopvar