// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: api/chat_service/chat.proto

package chatv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateChatIn struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	PatientId      string                 `protobuf:"bytes,3,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	ParticipantIds []string               `protobuf:"bytes,4,rep,name=participant_ids,json=participantIds,proto3" json:"participant_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateChatIn) Reset() {
	*x = CreateChatIn{}
	mi := &file_api_chat_service_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatIn) ProtoMessage() {}

func (x *CreateChatIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_service_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatIn.ProtoReflect.Descriptor instead.
func (*CreateChatIn) Descriptor() ([]byte, []int) {
	return file_api_chat_service_chat_proto_rawDescGZIP(), []int{0}
}

func (x *CreateChatIn) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateChatIn) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateChatIn) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *CreateChatIn) GetParticipantIds() []string {
	if x != nil {
		return x.ParticipantIds
	}
	return nil
}

type CreateChatOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatOut) Reset() {
	*x = CreateChatOut{}
	mi := &file_api_chat_service_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatOut) ProtoMessage() {}

func (x *CreateChatOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_service_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatOut.ProtoReflect.Descriptor instead.
func (*CreateChatOut) Descriptor() ([]byte, []int) {
	return file_api_chat_service_chat_proto_rawDescGZIP(), []int{1}
}

func (x *CreateChatOut) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type GetChatIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatIn) Reset() {
	*x = GetChatIn{}
	mi := &file_api_chat_service_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatIn) ProtoMessage() {}

func (x *GetChatIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_service_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatIn.ProtoReflect.Descriptor instead.
func (*GetChatIn) Descriptor() ([]byte, []int) {
	return file_api_chat_service_chat_proto_rawDescGZIP(), []int{2}
}

func (x *GetChatIn) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type Chat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PatientId      string                 `protobuf:"bytes,4,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	ParticipantIds []string               `protobuf:"bytes,5,rep,name=participant_ids,json=participantIds,proto3" json:"participant_ids,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_api_chat_service_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_service_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_api_chat_service_chat_proto_rawDescGZIP(), []int{3}
}

func (x *Chat) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Chat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Chat) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Chat) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *Chat) GetParticipantIds() []string {
	if x != nil {
		return x.ParticipantIds
	}
	return nil
}

func (x *Chat) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetChatOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chat          *Chat                  `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatOut) Reset() {
	*x = GetChatOut{}
	mi := &file_api_chat_service_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatOut) ProtoMessage() {}

func (x *GetChatOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_service_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatOut.ProtoReflect.Descriptor instead.
func (*GetChatOut) Descriptor() ([]byte, []int) {
	return file_api_chat_service_chat_proto_rawDescGZIP(), []int{4}
}

func (x *GetChatOut) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

type GetChatsIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DoctorId      string                 `protobuf:"bytes,1,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatsIn) Reset() {
	*x = GetChatsIn{}
	mi := &file_api_chat_service_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatsIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatsIn) ProtoMessage() {}

func (x *GetChatsIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_service_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatsIn.ProtoReflect.Descriptor instead.
func (*GetChatsIn) Descriptor() ([]byte, []int) {
	return file_api_chat_service_chat_proto_rawDescGZIP(), []int{5}
}

func (x *GetChatsIn) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

type GetChatsOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*Chat                `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatsOut) Reset() {
	*x = GetChatsOut{}
	mi := &file_api_chat_service_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatsOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatsOut) ProtoMessage() {}

func (x *GetChatsOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_service_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatsOut.ProtoReflect.Descriptor instead.
func (*GetChatsOut) Descriptor() ([]byte, []int) {
	return file_api_chat_service_chat_proto_rawDescGZIP(), []int{6}
}

func (x *GetChatsOut) GetChats() []*Chat {
	if x != nil {
		return x.Chats
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChatId        string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_chat_service_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_service_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_chat_service_chat_proto_rawDescGZIP(), []int{7}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *Message) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetChatHistoryIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatHistoryIn) Reset() {
	*x = GetChatHistoryIn{}
	mi := &file_api_chat_service_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatHistoryIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatHistoryIn) ProtoMessage() {}

func (x *GetChatHistoryIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_service_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatHistoryIn.ProtoReflect.Descriptor instead.
func (*GetChatHistoryIn) Descriptor() ([]byte, []int) {
	return file_api_chat_service_chat_proto_rawDescGZIP(), []int{8}
}

func (x *GetChatHistoryIn) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *GetChatHistoryIn) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetChatHistoryIn) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetChatHistoryOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatHistoryOut) Reset() {
	*x = GetChatHistoryOut{}
	mi := &file_api_chat_service_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatHistoryOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatHistoryOut) ProtoMessage() {}

func (x *GetChatHistoryOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_service_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatHistoryOut.ProtoReflect.Descriptor instead.
func (*GetChatHistoryOut) Descriptor() ([]byte, []int) {
	return file_api_chat_service_chat_proto_rawDescGZIP(), []int{9}
}

func (x *GetChatHistoryOut) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_api_chat_service_chat_proto protoreflect.FileDescriptor

const file_api_chat_service_chat_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/chat_service/chat.proto\x12\achat.v1\"\x8c\x01\n" +
	"\fCreateChatIn\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x03 \x01(\tR\tpatientId\x12'\n" +
	"\x0fparticipant_ids\x18\x04 \x03(\tR\x0eparticipantIds\"(\n" +
	"\rCreateChatOut\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"$\n" +
	"\tGetChatIn\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"\xb3\x01\n" +
	"\x04Chat\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x04 \x01(\tR\tpatientId\x12'\n" +
	"\x0fparticipant_ids\x18\x05 \x03(\tR\x0eparticipantIds\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"/\n" +
	"\n" +
	"GetChatOut\x12!\n" +
	"\x04chat\x18\x01 \x01(\v2\r.chat.v1.ChatR\x04chat\")\n" +
	"\n" +
	"GetChatsIn\x12\x1b\n" +
	"\tdoctor_id\x18\x01 \x01(\tR\bdoctorId\"2\n" +
	"\vGetChatsOut\x12#\n" +
	"\x05chats\x18\x01 \x03(\v2\r.chat.v1.ChatR\x05chats\"\x88\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"Y\n" +
	"\x10GetChatHistoryIn\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"A\n" +
	"\x11GetChatHistoryOut\x12,\n" +
	"\bmessages\x18\x01 \x03(\v2\x10.chat.v1.MessageR\bmessages2\xfa\x01\n" +
	"\aChatSrv\x12;\n" +
	"\n" +
	"CreateChat\x12\x15.chat.v1.CreateChatIn\x1a\x16.chat.v1.CreateChatOut\x125\n" +
	"\bGetChats\x12\x13.chat.v1.GetChatsIn\x1a\x14.chat.v1.GetChatsOut\x122\n" +
	"\aGetChat\x12\x12.chat.v1.GetChatIn\x1a\x13.chat.v1.GetChatOut\x12G\n" +
	"\x0eGetChatHistory\x12\x19.chat.v1.GetChatHistoryIn\x1a\x1a.chat.v1.GetChatHistoryOutB)Z'chat_service/internal/pb/chat/v1;chatv1b\x06proto3"

var (
	file_api_chat_service_chat_proto_rawDescOnce sync.Once
	file_api_chat_service_chat_proto_rawDescData []byte
)

func file_api_chat_service_chat_proto_rawDescGZIP() []byte {
	file_api_chat_service_chat_proto_rawDescOnce.Do(func() {
		file_api_chat_service_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_chat_service_chat_proto_rawDesc), len(file_api_chat_service_chat_proto_rawDesc)))
	})
	return file_api_chat_service_chat_proto_rawDescData
}

var file_api_chat_service_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_chat_service_chat_proto_goTypes = []any{
	(*CreateChatIn)(nil),      // 0: chat.v1.CreateChatIn
	(*CreateChatOut)(nil),     // 1: chat.v1.CreateChatOut
	(*GetChatIn)(nil),         // 2: chat.v1.GetChatIn
	(*Chat)(nil),              // 3: chat.v1.Chat
	(*GetChatOut)(nil),        // 4: chat.v1.GetChatOut
	(*GetChatsIn)(nil),        // 5: chat.v1.GetChatsIn
	(*GetChatsOut)(nil),       // 6: chat.v1.GetChatsOut
	(*Message)(nil),           // 7: chat.v1.Message
	(*GetChatHistoryIn)(nil),  // 8: chat.v1.GetChatHistoryIn
	(*GetChatHistoryOut)(nil), // 9: chat.v1.GetChatHistoryOut
}
var file_api_chat_service_chat_proto_depIdxs = []int32{
	3, // 0: chat.v1.GetChatOut.chat:type_name -> chat.v1.Chat
	3, // 1: chat.v1.GetChatsOut.chats:type_name -> chat.v1.Chat
	7, // 2: chat.v1.GetChatHistoryOut.messages:type_name -> chat.v1.Message
	0, // 3: chat.v1.ChatSrv.CreateChat:input_type -> chat.v1.CreateChatIn
	5, // 4: chat.v1.ChatSrv.GetChats:input_type -> chat.v1.GetChatsIn
	2, // 5: chat.v1.ChatSrv.GetChat:input_type -> chat.v1.GetChatIn
	8, // 6: chat.v1.ChatSrv.GetChatHistory:input_type -> chat.v1.GetChatHistoryIn
	1, // 7: chat.v1.ChatSrv.CreateChat:output_type -> chat.v1.CreateChatOut
	6, // 8: chat.v1.ChatSrv.GetChats:output_type -> chat.v1.GetChatsOut
	4, // 9: chat.v1.ChatSrv.GetChat:output_type -> chat.v1.GetChatOut
	9, // 10: chat.v1.ChatSrv.GetChatHistory:output_type -> chat.v1.GetChatHistoryOut
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_chat_service_chat_proto_init() }
func file_api_chat_service_chat_proto_init() {
	if File_api_chat_service_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_chat_service_chat_proto_rawDesc), len(file_api_chat_service_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_chat_service_chat_proto_goTypes,
		DependencyIndexes: file_api_chat_service_chat_proto_depIdxs,
		MessageInfos:      file_api_chat_service_chat_proto_msgTypes,
	}.Build()
	File_api_chat_service_chat_proto = out.File
	file_api_chat_service_chat_proto_goTypes = nil
	file_api_chat_service_chat_proto_depIdxs = nil
}
