version: '3'

includes:
  root_tasks: ../Taskfile.yml

tasks:
  build:
    - task: root_tasks:build

  run:
    deps: [build]
    env:
      S3_ENDPOINT: localhost:9000
      S3_ACCESS_TOKEN: BLAD0h1rTDPG70DQ7PUd
      S3_SECRET_TOKEN: qtbVnWFWlu7hpIGt8A3HPYpOPiHF6cECHzaicigz

    cmds:
      - ./bin/server

  default:
    - task: root_tasks:build
