version: "3"

vars:
  VENDOR_PROTOGEN: "../vendor.protogen"

dotenv: [".env.example"]
#TODO: написать проверки в коде при подключении ко всему (к S3 и т.д)
#TODO: универсализировать TaskFile, вынести все на верхний уровень
tasks:
  bin-deps:
    cmds:
      - GOBIN=$(pwd)/bin go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - GOBIN=$(pwd)/bin go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

  codegen:
    vars:
      proto_libs:
        sh: find {{.VENDOR_PROTOGEN}} -mindepth 1 -maxdepth 1 -type d | xargs echo
      proto_files:
        sh: find proto -type f -name "*.proto" | xargs echo

    cmds:
      - task: bin-deps
      - for: { var: proto_files }
        cmd: >
          protoc
          -I {{dir .ITEM}}
          --plugin=protoc-gen-go=$(pwd)/bin/protoc-gen-go
          --plugin=protoc-gen-go-grpc=$(pwd)/bin/protoc-gen-go-grpc
          {{range $lib := splitList " " .proto_libs}}-I {{$lib}} {{end}}
          --experimental_allow_proto3_optional
          --go_out . --go-grpc_out .
          {{.ITEM}}
  style:
    cmds:
      - go fmt ./...
      - go tool goimports -w .
      - go tool gofumpt -l -w .

  build:
    cmds:
      - task: style
      - go build -v -o bin/service cmd/service/main.go

  run:
    cmds:
      # - task: build
      - ./bin/service
  
  # TODO: перевести все на go tool go 1.24
  e2e:
    cmds:
      - go test -v -count=1 ./tests/e2e/... -tags=e2e -run TestTestSuite -testify.m TestCreateUpdateDeleteGetSegment_Success

  migration-up:
    cmds:
      - go tool goose -dir db/migrations up

  migration-down:
    cmds:
      - go tool goose -dir db/migrations down
