basePath: /api/v1
definitions:
  med.Doctor:
    properties:
      desc:
        type: string
      fullname:
        type: string
      id:
        type: string
      job:
        type: string
      org:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample API for demonstration.
  title: Example API
  version: "1.0"
paths:
  /med/doctors:
    post:
      description: Получает информацию о враче
      parameters:
      - description: access_token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/med.Doctor'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Получить информацию о враче
      tags:
      - doctors
  /uzi/uzis:
    post:
      description: Загружает узи на обработку
      parameters:
      - description: access_token
        in: header
        name: token
        required: true
        type: string
      - description: uzi file. (обязательно с .tiff/.png)
        in: formData
        name: file
        required: true
        type: file
      - description: проекция узи
        in: formData
        name: projection
        required: true
        type: string
      - description: id пациента
        in: formData
        name: patient_id
        required: true
        type: string
      - description: id узи апапапапарата
        in: formData
        name: device_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: molodec
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Загружает узи на обработку
      tags:
      - uzi
swagger: "2.0"
