version: '3'

vars:
  proto_libs_path: '{{.proto_libs | default "../vendor.protogen"}}'
  proto_target: '{{.proto_target | default "events.proto"}}'
  proto_out: '{{.proto_out | default "."}}'
  swagger_out: '{{.swagger_out | default "."}}'

tasks:
  generate:
    vars:
      LIBS_DIRS:
        sh: find {{.proto_libs_path}} -mindepth 1 -maxdepth 1 -type d | xargs echo
    cmds:
      - > 
        protoc
        -I {{dir .proto_target}}
        {{range $proto_lib := splitList " " .LIBS_DIRS}}-I {{$proto_lib}} {{end}}
        --go_out {{.proto_out}} --go_opt paths=source_relative
        {{.proto_target}}
      - >
        python3 -m grpc_tools.protoc
        {{range $proto_lib := splitList " " .LIBS_DIRS}}-I {{$proto_lib}} {{end}}
        --python_out={{.proto_out}} 
        --proto_path={{.proto_out}}
        {{.proto_target}}

    sources:
      - '{{.proto_target}}'

    generates:
      - '{{.proto_out}}/*.pb.go'
      - '{{.proto_out}}/*_pb2.py'

  default:
    cmds:
      - task: generate